services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - custom-network
    environment:
      POSTGRES_USER: Marco
      POSTGRES_PASSWORD: password
      POSTGRES_DB: localdb
      PGDATA: /data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
networks:
  custom-network:
    driver: bridge