spring:
  threads:
    virtual:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/localdb
    username: Marco
    password:
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/localdb
    user: Marco
    password:
    locations: classpath:db/migration
    driver-class-name: org.postgresql.Driver

# in milliseconds
cleanup:
  time: 5000
custom:
  server:
    url: http://localhost:8080/