services:
  build-init:
    image: maven:3.9-amazoncorretto-21
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    command: mvn clean package -DskipTests -T 1C

  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    networks:
      - custom-network
    environment:
      POSTGRES_USER: Marco
      POSTGRES_PASSWORD: password
      POSTGRES_DB: localdb
      PGDATA: /data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust

  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - custom-network
    depends_on:
      build-init:
        condition: service_completed_successfully
      database:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped
    scale: 5
networks:
  custom-network:
    driver: bridge